# Generated by Django 5.1.2 on 2024-11-01 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '11499_add_editlog_resourceinstance_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('config', models.JSONField()),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.graphmodel')),
            ],
            options={
                'db_table': 'report_config',
                'managed': True,
            },
        ),
    ]
