# Generated by Django 5.1.3 on 2024-11-07 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arches_provenance", "0002_add_editable_report"),
        ("models", "11499_add_editlog_resourceinstance_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportconfig",
            name="graph",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report",
                to="models.graphmodel",
            ),
        ),
    ]
