# Generated by Django 5.1.3 on 2024-11-13 09:25

import arches_provenance.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arches_provenance", "0002_add_editable_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportconfig",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=arches_provenance.utils.PrettyJSONEncoder,
            ),
        ),
    ]
