# Generated by Django 4.2.19 on 2025-03-05 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11499_add_editlog_resourceinstance_idx"),
        ("arches_provenance", "11500_change_default_standard_search"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportconfig",
            name="graph",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("isresource", True)),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report",
                to="models.graphmodel",
            ),
        ),
    ]
