version: '3.8'
name: arches-provenance7-0
services:
    arches-provenance7-0:
      container_name: arches-provenance7-0
      image: getty/arches-provenance7-0
      build:
        args:
          ARCHES_CORE_HOST_DIR: ../arches/
        context: ..
        dockerfile: arches_provenance/Dockerfile
      command: run_arches
      volumes:  
        - ${ARCHES_CORE_HOST_DIR:-../arches/}:/web_root/arches
        - ./:/web_root/arches_provenance
      env_file:
        - ./docker/env_file.env
      ports:
        - 8017:8000
        - 5687:5678
      stdin_open: true
      tty: true

    arches-provenance-webpack-7-0:
      container_name: arches-provenance-webpack-7-0
      image: fargeo/arches-provenance-webpack-7-0
      build:
        args:
          ARCHES_CORE_HOST_DIR: ../arches/
        context: ..
        dockerfile: arches_provenance/docker/webpack/Dockerfile
      command: run_webpack
      volumes:
        - ${ARCHES_CORE_HOST_DIR:-../arches/}:/web_root/arches
        - ./:/web_root/arches_provenance
      env_file:
        - ./docker/webpack/env_file.env
      ports:
        - 8027:8021
      stdin_open: true
      tty: true

networks:
  default:
    external: true
    name: arches7-0-dev

volumes:
    arches-log-arches-provenance7-0:
    arches-static-arches-provenance7-0:
